include-languages:
- kotlin
- java
exclude-languages:
  - go
include-labels:
- adoptme
- contributions welcome
- help wanted
- good first issue
- PR welcome
- noob friendly
- ideal for contribution
- low hanging fruit
- easy
- E-easy
exclude-repositories:
- platan/idea-gradle-dependencies-formatter
- AdoptOpenJDK/jsplitpkgscan
- gradle/kotlin-dsl
exclude-issues:
- https://github.com/crate/crate/issues/882
