username: IgorPerikov
languages:
- kotlin
- java
- go
labels:
- adoptme
- contributions welcome
- help wanted
- enhancement
- good first issue
- PR welcome
- noob friendly
- ideal for contribution
- easy
ignored-repos:
- balamaci/rxjava-walkthrough
- platan/idea-gradle-dependencies-formatter
- AdoptOpenJDK/jsplitpkgscan
- gradle/kotlin-dsl
ignored-issues:
- https://github.com/crate/crate/issues/882
